//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.aopkb.org/aop-xml", IsNullable=false)]
public partial class data {
    
    private dataChemical[] chemicalField;
    
    private dataBiologicalobject[] biologicalobjectField;
    
    private dataBiologicalprocess[] biologicalprocessField;
    
    private dataBiologicalaction[] biologicalactionField;
    
    private dataStressor[] stressorField;
    
    private dataTaxonomy[] taxonomyField;
    
    private dataKeyevent[] keyeventField;
    
    private dataKeyeventrelationship[] keyeventrelationshipField;
    
    private dataAop[] aopField;
    
    private dataVendorspecific vendorspecificField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chemical")]
    public dataChemical[] chemical {
        get {
            return this.chemicalField;
        }
        set {
            this.chemicalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-object")]
    public dataBiologicalobject[] biologicalobject {
        get {
            return this.biologicalobjectField;
        }
        set {
            this.biologicalobjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-process")]
    public dataBiologicalprocess[] biologicalprocess {
        get {
            return this.biologicalprocessField;
        }
        set {
            this.biologicalprocessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-action")]
    public dataBiologicalaction[] biologicalaction {
        get {
            return this.biologicalactionField;
        }
        set {
            this.biologicalactionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stressor")]
    public dataStressor[] stressor {
        get {
            return this.stressorField;
        }
        set {
            this.stressorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("taxonomy")]
    public dataTaxonomy[] taxonomy {
        get {
            return this.taxonomyField;
        }
        set {
            this.taxonomyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key-event")]
    public dataKeyevent[] keyevent {
        get {
            return this.keyeventField;
        }
        set {
            this.keyeventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key-event-relationship")]
    public dataKeyeventrelationship[] keyeventrelationship {
        get {
            return this.keyeventrelationshipField;
        }
        set {
            this.keyeventrelationshipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("aop")]
    public dataAop[] aop {
        get {
            return this.aopField;
        }
        set {
            this.aopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vendor-specific")]
    public dataVendorspecific vendorspecific {
        get {
            return this.vendorspecificField;
        }
        set {
            this.vendorspecificField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataChemical {
    
    private string inchiField;
    
    private string casrnField;
    
    private string jcheminchikeyField;
    
    private string indigoinchikeyField;
    
    private string iupacnameField;
    
    private string smilesField;
    
    private string preferrednameField;
    
    private string[] synonymsField;
    
    private string formulaField;
    
    private byte[] structuraldiagram2dField;
    
    private string dsstoxidField;
    
    private System.DateTime creationtimestampField;
    
    private bool creationtimestampFieldSpecified;
    
    private System.DateTime lastmodificationtimestampField;
    
    private bool lastmodificationtimestampFieldSpecified;
    
    private string idField;
    
    /// <remarks/>
    public string inchi {
        get {
            return this.inchiField;
        }
        set {
            this.inchiField = value;
        }
    }
    
    /// <remarks/>
    public string casrn {
        get {
            return this.casrnField;
        }
        set {
            this.casrnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jchem-inchi-key")]
    public string jcheminchikey {
        get {
            return this.jcheminchikeyField;
        }
        set {
            this.jcheminchikeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("indigo-inchi-key")]
    public string indigoinchikey {
        get {
            return this.indigoinchikeyField;
        }
        set {
            this.indigoinchikeyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("iupac-name")]
    public string iupacname {
        get {
            return this.iupacnameField;
        }
        set {
            this.iupacnameField = value;
        }
    }
    
    /// <remarks/>
    public string smiles {
        get {
            return this.smilesField;
        }
        set {
            this.smilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("preferred-name")]
    public string preferredname {
        get {
            return this.preferrednameField;
        }
        set {
            this.preferrednameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("synonym", IsNullable=false)]
    public string[] synonyms {
        get {
            return this.synonymsField;
        }
        set {
            this.synonymsField = value;
        }
    }
    
    /// <remarks/>
    public string formula {
        get {
            return this.formulaField;
        }
        set {
            this.formulaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("structural-diagram-2d", DataType="hexBinary")]
    public byte[] structuraldiagram2d {
        get {
            return this.structuraldiagram2dField;
        }
        set {
            this.structuraldiagram2dField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dsstox-id")]
    public string dsstoxid {
        get {
            return this.dsstoxidField;
        }
        set {
            this.dsstoxidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationtimestampSpecified {
        get {
            return this.creationtimestampFieldSpecified;
        }
        set {
            this.creationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastmodificationtimestampSpecified {
        get {
            return this.lastmodificationtimestampFieldSpecified;
        }
        set {
            this.lastmodificationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aopkb.org/aop-xml")]
public partial class status {
    
    private statusWikistatus wikistatusField;
    
    private statusOecdstatus oecdstatusField;
    
    private statusSaaopstatus saaopstatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("wiki-status")]
    public statusWikistatus wikistatus {
        get {
            return this.wikistatusField;
        }
        set {
            this.wikistatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("oecd-status")]
    public statusOecdstatus oecdstatus {
        get {
            return this.oecdstatusField;
        }
        set {
            this.oecdstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("saaop-status")]
    public statusSaaopstatus saaopstatus {
        get {
            return this.saaopstatusField;
        }
        set {
            this.saaopstatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum statusWikistatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Open for Citation")]
    OpenforCitation,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Open for Adoption")]
    OpenforAdoption,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Open for Comment")]
    OpenforComment,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Not under Development")]
    NotunderDevelopment,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Under Development")]
    UnderDevelopment,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum statusOecdstatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("TFHA/WNT Endorsed")]
    TFHAWNTEndorsed,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("EAGMST Approved")]
    EAGMSTApproved,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("EAGMST Under Review")]
    EAGMSTUnderReview,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Under Development")]
    UnderDevelopment,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum statusSaaopstatus {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Included in OECD Work Plan")]
    IncludedinOECDWorkPlan,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Proposed for OECD Work Plan")]
    ProposedforOECDWorkPlan,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Under Development")]
    UnderDevelopment,
    
    /// <remarks/>
    Archived,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="evidence-type", Namespace="http://www.aopkb.org/aop-xml")]
public partial class evidencetype {
    
    private confidenceleveltype evidenceField;
    
    private string descriptionField;
    
    private string[] uriField;
    
    /// <remarks/>
    public confidenceleveltype evidence {
        get {
            return this.evidenceField;
        }
        set {
            this.evidenceField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uri")]
    public string[] uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="confidence-level-type", Namespace="http://www.aopkb.org/aop-xml")]
public enum confidenceleveltype {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Very strong")]
    Verystrong,
    
    /// <remarks/>
    Strong,
    
    /// <remarks/>
    Moderate,
    
    /// <remarks/>
    Weak,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("not specified")]
    notspecified,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="applicability-type", Namespace="http://www.aopkb.org/aop-xml")]
public partial class applicabilitytype {
    
    private applicabilitytypeSex[] sexField;
    
    private applicabilitytypeLifestage[] lifestageField;
    
    private applicabilitytypeTaxonomy[] taxonomyField;
    
    private string[] uriField;
    
    private string[] biologicalcompartmentField;
    
    private string[] timetomanifestationField;
    
    private string[] timetomanifestationrangeField;
    
    private string[] generationField;
    
    private string[] otherField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sex")]
    public applicabilitytypeSex[] sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("life-stage")]
    public applicabilitytypeLifestage[] lifestage {
        get {
            return this.lifestageField;
        }
        set {
            this.lifestageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("taxonomy")]
    public applicabilitytypeTaxonomy[] taxonomy {
        get {
            return this.taxonomyField;
        }
        set {
            this.taxonomyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uri")]
    public string[] uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-compartment")]
    public string[] biologicalcompartment {
        get {
            return this.biologicalcompartmentField;
        }
        set {
            this.biologicalcompartmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("time-to-manifestation")]
    public string[] timetomanifestation {
        get {
            return this.timetomanifestationField;
        }
        set {
            this.timetomanifestationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("time-to-manifestation-range")]
    public string[] timetomanifestationrange {
        get {
            return this.timetomanifestationrangeField;
        }
        set {
            this.timetomanifestationrangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("generation")]
    public string[] generation {
        get {
            return this.generationField;
        }
        set {
            this.generationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("other")]
    public string[] other {
        get {
            return this.otherField;
        }
        set {
            this.otherField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class applicabilitytypeSex : evidencetype {
    
    private applicabilitytypeSexSex sexField;
    
    private bool sexFieldSpecified;
    
    /// <remarks/>
    public applicabilitytypeSexSex sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sexSpecified {
        get {
            return this.sexFieldSpecified;
        }
        set {
            this.sexFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum applicabilitytypeSexSex {
    
    /// <remarks/>
    Male,
    
    /// <remarks/>
    Female,
    
    /// <remarks/>
    Mixed,
    
    /// <remarks/>
    Asexual,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Third Gender")]
    ThirdGender,
    
    /// <remarks/>
    Hermaphrodite,
    
    /// <remarks/>
    Unspecific,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class applicabilitytypeLifestage : evidencetype {
    
    private applicabilitytypeLifestageLifestage lifestageField;
    
    private bool lifestageFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("life-stage")]
    public applicabilitytypeLifestageLifestage lifestage {
        get {
            return this.lifestageField;
        }
        set {
            this.lifestageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lifestageSpecified {
        get {
            return this.lifestageFieldSpecified;
        }
        set {
            this.lifestageFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum applicabilitytypeLifestageLifestage {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Birth to < 1 month")]
    Birthto1month,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1 to < 3 months")]
    Item1to3months,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3 to < 6 months")]
    Item3to6months,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6 to < 12 months")]
    Item6to12months,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1 to < 2 years")]
    Item1to2years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2 to < 3 years")]
    Item2to3years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3 to < 6 years")]
    Item3to6years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6 to < 11 years")]
    Item6to11years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11 to < 16 years")]
    Item11to16years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16 to < 21 years")]
    Item16to21years,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Nursing Child")]
    NursingChild,
    
    /// <remarks/>
    Pregnancy,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Old Age")]
    OldAge,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Not Otherwise Specified")]
    NotOtherwiseSpecified,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Lactating Mother")]
    LactatingMother,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Conception to < Fetal")]
    ConceptiontoFetal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Fetal to Parturition")]
    FetaltoParturition,
    
    /// <remarks/>
    Foetal,
    
    /// <remarks/>
    Embryo,
    
    /// <remarks/>
    Juvenile,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Adult, reproductively mature")]
    Adultreproductivelymature,
    
    /// <remarks/>
    Perinatal,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("During development and at adulthood")]
    Duringdevelopmentandatadulthood,
    
    /// <remarks/>
    Adults,
    
    /// <remarks/>
    Adult,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("During brain development, adulthood and aging")]
    Duringbraindevelopmentadulthoodandaging,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("During brain development")]
    Duringbraindevelopment,
    
    /// <remarks/>
    Human,
    
    /// <remarks/>
    Development,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("All life stages")]
    Alllifestages,
    
    /// <remarks/>
    Fetal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class applicabilitytypeTaxonomy : evidencetype {
    
    private string taxonomyidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("taxonomy-id")]
    public string taxonomyid {
        get {
            return this.taxonomyidField;
        }
        set {
            this.taxonomyidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="substance-info", Namespace="http://www.aopkb.org/aop-xml")]
public partial class substanceinfo {
    
    private string titleField;
    
    private string idField;
    
    private string[] typeField;
    
    private string[] iucnameField;
    
    private propertyvalues[] substancepropertiesField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type")]
    public string[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("iuc-name")]
    public string[] iucname {
        get {
            return this.iucnameField;
        }
        set {
            this.iucnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("substance-properties")]
    public propertyvalues[] substanceproperties {
        get {
            return this.substancepropertiesField;
        }
        set {
            this.substancepropertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="property-values", Namespace="http://www.aopkb.org/aop-xml")]
public partial class propertyvalues {
    
    private string propertyField;
    
    private string valueField;
    
    private string unitsField;
    
    private string conditionsField;
    
    private string sourceField;
    
    /// <remarks/>
    public string property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public string conditions {
        get {
            return this.conditionsField;
        }
        set {
            this.conditionsField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="qa-type", Namespace="http://www.aopkb.org/aop-xml")]
public partial class qatype {
    
    private string[] contributorField;
    
    private string[] reviewerField;
    
    private string[] sealofapprovalField;
    
    private System.DateTime lastmodifiedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contributor")]
    public string[] contributor {
        get {
            return this.contributorField;
        }
        set {
            this.contributorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reviewer")]
    public string[] reviewer {
        get {
            return this.reviewerField;
        }
        set {
            this.reviewerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seal-of-approval")]
    public string[] sealofapproval {
        get {
            return this.sealofapprovalField;
        }
        set {
            this.sealofapprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modified")]
    public System.DateTime lastmodified {
        get {
            return this.lastmodifiedField;
        }
        set {
            this.lastmodifiedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="biological-term-type", Namespace="http://www.aopkb.org/aop-xml")]
public partial class biologicaltermtype {
    
    private string sourceidField;
    
    private string sourceField;
    
    private string nameField;
    
    private string synonymField;
    
    private System.DateTime creationtimestampField;
    
    private bool creationtimestampFieldSpecified;
    
    private System.DateTime lastmodificationtimestampField;
    
    private bool lastmodificationtimestampFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("source-id")]
    public string sourceid {
        get {
            return this.sourceidField;
        }
        set {
            this.sourceidField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string synonym {
        get {
            return this.synonymField;
        }
        set {
            this.synonymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationtimestampSpecified {
        get {
            return this.creationtimestampFieldSpecified;
        }
        set {
            this.creationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastmodificationtimestampSpecified {
        get {
            return this.lastmodificationtimestampFieldSpecified;
        }
        set {
            this.lastmodificationtimestampFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataBiologicalobject : biologicaltermtype {
    
    private biologicalorganizationleveltype biologicalorganizationField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-organization")]
    public biologicalorganizationleveltype biologicalorganization {
        get {
            return this.biologicalorganizationField;
        }
        set {
            this.biologicalorganizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="biological-organization-level-type", Namespace="http://www.aopkb.org/aop-xml")]
public enum biologicalorganizationleveltype {
    
    /// <remarks/>
    Molecular,
    
    /// <remarks/>
    Organelle,
    
    /// <remarks/>
    Cellular,
    
    /// <remarks/>
    Tissue,
    
    /// <remarks/>
    Organ,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Organ System")]
    OrganSystem,
    
    /// <remarks/>
    Individual,
    
    /// <remarks/>
    Population,
    
    /// <remarks/>
    Species,
    
    /// <remarks/>
    Communities,
    
    /// <remarks/>
    Ecosystem,
    
    /// <remarks/>
    Biosphere,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataBiologicalprocess : biologicaltermtype {
    
    private biologicalorganizationleveltype biologicalorganizationField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-organization")]
    public biologicalorganizationleveltype biologicalorganization {
        get {
            return this.biologicalorganizationField;
        }
        set {
            this.biologicalorganizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataBiologicalaction : biologicaltermtype {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataStressor {
    
    private string titleField;
    
    private qatype qualityassuranceField;
    
    private string nameField;
    
    private string descriptionField;
    
    private dataStressorChemicalinitiator[] chemicalsField;
    
    private propertyvalues[] structuralpropertiesField;
    
    private string[] synonymField;
    
    private substanceinfo[] associatedsubstancesField;
    
    private string[] linkField;
    
    private string exposurecharacterizationField;
    
    private System.DateTime creationtimestampField;
    
    private bool creationtimestampFieldSpecified;
    
    private System.DateTime lastmodificationtimestampField;
    
    private bool lastmodificationtimestampFieldSpecified;
    
    private string idField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quality-assurance")]
    public qatype qualityassurance {
        get {
            return this.qualityassuranceField;
        }
        set {
            this.qualityassuranceField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("chemical-initiator", IsNullable=false)]
    public dataStressorChemicalinitiator[] chemicals {
        get {
            return this.chemicalsField;
        }
        set {
            this.chemicalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("structural-properties")]
    public propertyvalues[] structuralproperties {
        get {
            return this.structuralpropertiesField;
        }
        set {
            this.structuralpropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("synonym")]
    public string[] synonym {
        get {
            return this.synonymField;
        }
        set {
            this.synonymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("associated-substances")]
    public substanceinfo[] associatedsubstances {
        get {
            return this.associatedsubstancesField;
        }
        set {
            this.associatedsubstancesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("link")]
    public string[] link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exposure-characterization")]
    public string exposurecharacterization {
        get {
            return this.exposurecharacterizationField;
        }
        set {
            this.exposurecharacterizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationtimestampSpecified {
        get {
            return this.creationtimestampFieldSpecified;
        }
        set {
            this.creationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastmodificationtimestampSpecified {
        get {
            return this.lastmodificationtimestampFieldSpecified;
        }
        set {
            this.lastmodificationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataStressorChemicalinitiator {
    
    private string chemicalidField;
    
    private string usertermField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("chemical-id")]
    public string chemicalid {
        get {
            return this.chemicalidField;
        }
        set {
            this.chemicalidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("user-term")]
    public string userterm {
        get {
            return this.usertermField;
        }
        set {
            this.usertermField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataTaxonomy : biologicaltermtype {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyevent {
    
    private string titleField;
    
    private string shortnameField;
    
    private System.DateTime creationtimestampField;
    
    private bool creationtimestampFieldSpecified;
    
    private System.DateTime lastmodificationtimestampField;
    
    private bool lastmodificationtimestampFieldSpecified;
    
    private biologicalorganizationleveltype biologicalorganizationlevelField;
    
    private bool biologicalorganizationlevelFieldSpecified;
    
    private string descriptionField;
    
    private string measurementmethodologyField;
    
    private string evidencesupportingtaxonomicapplicabilityField;
    
    private string referencesField;
    
    private biologicaltermtype organtermField;
    
    private biologicaltermtype celltermField;
    
    private qatype qualityassuranceField;
    
    private applicabilitytype applicabilityField;
    
    private dataKeyeventSource sourceField;
    
    private bool sourceFieldSpecified;
    
    private string sourceinternalidField;
    
    private string uriField;
    
    private string associatedtestsField;
    
    private dataKeyeventBiologicalevent[] biologicaleventsField;
    
    private dataKeyeventKeyeventstressor[] keyeventstressorsField;
    
    private string idField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("short-name")]
    public string shortname {
        get {
            return this.shortnameField;
        }
        set {
            this.shortnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationtimestampSpecified {
        get {
            return this.creationtimestampFieldSpecified;
        }
        set {
            this.creationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastmodificationtimestampSpecified {
        get {
            return this.lastmodificationtimestampFieldSpecified;
        }
        set {
            this.lastmodificationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-organization-level")]
    public biologicalorganizationleveltype biologicalorganizationlevel {
        get {
            return this.biologicalorganizationlevelField;
        }
        set {
            this.biologicalorganizationlevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool biologicalorganizationlevelSpecified {
        get {
            return this.biologicalorganizationlevelFieldSpecified;
        }
        set {
            this.biologicalorganizationlevelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("measurement-methodology")]
    public string measurementmethodology {
        get {
            return this.measurementmethodologyField;
        }
        set {
            this.measurementmethodologyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("evidence-supporting-taxonomic-applicability")]
    public string evidencesupportingtaxonomicapplicability {
        get {
            return this.evidencesupportingtaxonomicapplicabilityField;
        }
        set {
            this.evidencesupportingtaxonomicapplicabilityField = value;
        }
    }
    
    /// <remarks/>
    public string references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organ-term")]
    public biologicaltermtype organterm {
        get {
            return this.organtermField;
        }
        set {
            this.organtermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cell-term")]
    public biologicaltermtype cellterm {
        get {
            return this.celltermField;
        }
        set {
            this.celltermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quality-assurance")]
    public qatype qualityassurance {
        get {
            return this.qualityassuranceField;
        }
        set {
            this.qualityassuranceField = value;
        }
    }
    
    /// <remarks/>
    public applicabilitytype applicability {
        get {
            return this.applicabilityField;
        }
        set {
            this.applicabilityField = value;
        }
    }
    
    /// <remarks/>
    public dataKeyeventSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sourceSpecified {
        get {
            return this.sourceFieldSpecified;
        }
        set {
            this.sourceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("source-internal-id")]
    public string sourceinternalid {
        get {
            return this.sourceinternalidField;
        }
        set {
            this.sourceinternalidField = value;
        }
    }
    
    /// <remarks/>
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("associated-tests")]
    public string associatedtests {
        get {
            return this.associatedtestsField;
        }
        set {
            this.associatedtestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("biological-events")]
    [System.Xml.Serialization.XmlArrayItemAttribute("biological-event", IsNullable=false)]
    public dataKeyeventBiologicalevent[] biologicalevents {
        get {
            return this.biologicaleventsField;
        }
        set {
            this.biologicaleventsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("key-event-stressors")]
    [System.Xml.Serialization.XmlArrayItemAttribute("key-event-stressor", IsNullable=false)]
    public dataKeyeventKeyeventstressor[] keyeventstressors {
        get {
            return this.keyeventstressorsField;
        }
        set {
            this.keyeventstressorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum dataKeyeventSource {
    
    /// <remarks/>
    AOPWiki,
    
    /// <remarks/>
    Effectopedia,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Intermediate Effects DB")]
    IntermediateEffectsDB,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("AOP Xplorer")]
    AOPXplorer,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventBiologicalevent {
    
    private string objectidField;
    
    private string processidField;
    
    private string actionidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("object-id")]
    public string objectid {
        get {
            return this.objectidField;
        }
        set {
            this.objectidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("process-id")]
    public string processid {
        get {
            return this.processidField;
        }
        set {
            this.processidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("action-id")]
    public string actionid {
        get {
            return this.actionidField;
        }
        set {
            this.actionidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventKeyeventstressor : evidencetype {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventrelationship {
    
    private dataKeyeventrelationshipTitle titleField;
    
    private qatype qualityassuranceField;
    
    private string descriptionField;
    
    private string temporalconcordanceField;
    
    private dataKeyeventrelationshipWeightofevidence weightofevidenceField;
    
    private dataKeyeventrelationshipQuantitativeunderstanding quantitativeunderstandingField;
    
    private applicabilitytype taxonomicapplicabilityField;
    
    private string evidencesupportingtaxonomicapplicabilityField;
    
    private dataKeyeventrelationshipSource sourceField;
    
    private bool sourceFieldSpecified;
    
    private string sourceinternalidField;
    
    private System.DateTime creationtimestampField;
    
    private bool creationtimestampFieldSpecified;
    
    private System.DateTime lastmodificationtimestampField;
    
    private bool lastmodificationtimestampFieldSpecified;
    
    private string referencesField;
    
    private string idField;
    
    /// <remarks/>
    public dataKeyeventrelationshipTitle title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quality-assurance")]
    public qatype qualityassurance {
        get {
            return this.qualityassuranceField;
        }
        set {
            this.qualityassuranceField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("temporal-concordance")]
    public string temporalconcordance {
        get {
            return this.temporalconcordanceField;
        }
        set {
            this.temporalconcordanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weight-of-evidence")]
    public dataKeyeventrelationshipWeightofevidence weightofevidence {
        get {
            return this.weightofevidenceField;
        }
        set {
            this.weightofevidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quantitative-understanding")]
    public dataKeyeventrelationshipQuantitativeunderstanding quantitativeunderstanding {
        get {
            return this.quantitativeunderstandingField;
        }
        set {
            this.quantitativeunderstandingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("taxonomic-applicability")]
    public applicabilitytype taxonomicapplicability {
        get {
            return this.taxonomicapplicabilityField;
        }
        set {
            this.taxonomicapplicabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("evidence-supporting-taxonomic-applicability")]
    public string evidencesupportingtaxonomicapplicability {
        get {
            return this.evidencesupportingtaxonomicapplicabilityField;
        }
        set {
            this.evidencesupportingtaxonomicapplicabilityField = value;
        }
    }
    
    /// <remarks/>
    public dataKeyeventrelationshipSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sourceSpecified {
        get {
            return this.sourceFieldSpecified;
        }
        set {
            this.sourceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("source-internal-id")]
    public string sourceinternalid {
        get {
            return this.sourceinternalidField;
        }
        set {
            this.sourceinternalidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationtimestampSpecified {
        get {
            return this.creationtimestampFieldSpecified;
        }
        set {
            this.creationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastmodificationtimestampSpecified {
        get {
            return this.lastmodificationtimestampFieldSpecified;
        }
        set {
            this.lastmodificationtimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventrelationshipTitle {
    
    private string upstreamidField;
    
    private string downstreamidField;
    
    private dataKeyeventrelationshipTitleDetaillevel detaillevelField;
    
    public dataKeyeventrelationshipTitle() {
        this.detaillevelField = dataKeyeventrelationshipTitleDetaillevel.Hypothetical;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("upstream-id")]
    public string upstreamid {
        get {
            return this.upstreamidField;
        }
        set {
            this.upstreamidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("downstream-id")]
    public string downstreamid {
        get {
            return this.downstreamidField;
        }
        set {
            this.downstreamidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detail-level")]
    [System.ComponentModel.DefaultValueAttribute(dataKeyeventrelationshipTitleDetaillevel.Hypothetical)]
    public dataKeyeventrelationshipTitleDetaillevel detaillevel {
        get {
            return this.detaillevelField;
        }
        set {
            this.detaillevelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum dataKeyeventrelationshipTitleDetaillevel {
    
    /// <remarks/>
    Hypothetical,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("One to One")]
    OnetoOne,
    
    /// <remarks/>
    Proportional,
    
    /// <remarks/>
    Threshold,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Response-Response")]
    ResponseResponse,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventrelationshipWeightofevidence {
    
    private string valueField;
    
    private string biologicalplausibilityField;
    
    private string empericalsupportlinkageField;
    
    private string uncertaintiesorinconsistenciesField;
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biological-plausibility")]
    public string biologicalplausibility {
        get {
            return this.biologicalplausibilityField;
        }
        set {
            this.biologicalplausibilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("emperical-support-linkage")]
    public string empericalsupportlinkage {
        get {
            return this.empericalsupportlinkageField;
        }
        set {
            this.empericalsupportlinkageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uncertainties-or-inconsistencies")]
    public string uncertaintiesorinconsistencies {
        get {
            return this.uncertaintiesorinconsistenciesField;
        }
        set {
            this.uncertaintiesorinconsistenciesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataKeyeventrelationshipQuantitativeunderstanding {
    
    private string descriptionField;
    
    private string supportevidenceField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("support-evidence")]
    public string supportevidence {
        get {
            return this.supportevidenceField;
        }
        set {
            this.supportevidenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum dataKeyeventrelationshipSource {
    
    /// <remarks/>
    AOPWiki,
    
    /// <remarks/>
    Effectopedia,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Intermediate Effects DB")]
    IntermediateEffectsDB,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("AOP Xplorer")]
    AOPXplorer,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAop {
    
    private string titleField;
    
    private string shortnameField;
    
    private string authorsField;
    
    private status statusField;
    
    private System.DateTime creationtimestampField;
    
    private System.DateTime lastmodificationtimestampField;
    
    private string abstractField;
    
    private string backgroundField;
    
    private dataAopMolecularinitiatingevent[] molecularinitiatingeventField;
    
    private dataAopAdverseoutcome[] adverseoutcomeField;
    
    private dataAopRelationship[] keyeventrelationshipsField;
    
    private object[] essentialitysupportField;
    
    private dataAopKeyeventessentiality[] keyeventessentialityField;
    
    private applicabilitytype applicabilityField;
    
    private dataAopOverallassessment overallassessmentField;
    
    private string potentialapplicationsField;
    
    private dataAopSource sourceField;
    
    private bool sourceFieldSpecified;
    
    private string sourceinternalidField;
    
    private string[] uriField;
    
    private string referencesField;
    
    private dataAopAopstressor[] aopstressorsField;
    
    private string idField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("short-name")]
    public string shortname {
        get {
            return this.shortnameField;
        }
        set {
            this.shortnameField = value;
        }
    }
    
    /// <remarks/>
    public string authors {
        get {
            return this.authorsField;
        }
        set {
            this.authorsField = value;
        }
    }
    
    /// <remarks/>
    public status status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("creation-timestamp")]
    public System.DateTime creationtimestamp {
        get {
            return this.creationtimestampField;
        }
        set {
            this.creationtimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("last-modification-timestamp")]
    public System.DateTime lastmodificationtimestamp {
        get {
            return this.lastmodificationtimestampField;
        }
        set {
            this.lastmodificationtimestampField = value;
        }
    }
    
    /// <remarks/>
    public string @abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    public string background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("molecular-initiating-event")]
    public dataAopMolecularinitiatingevent[] molecularinitiatingevent {
        get {
            return this.molecularinitiatingeventField;
        }
        set {
            this.molecularinitiatingeventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adverse-outcome")]
    public dataAopAdverseoutcome[] adverseoutcome {
        get {
            return this.adverseoutcomeField;
        }
        set {
            this.adverseoutcomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("key-event-relationships")]
    [System.Xml.Serialization.XmlArrayItemAttribute("relationship", IsNullable=false)]
    public dataAopRelationship[] keyeventrelationships {
        get {
            return this.keyeventrelationshipsField;
        }
        set {
            this.keyeventrelationshipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("essentiality-support")]
    public object[] essentialitysupport {
        get {
            return this.essentialitysupportField;
        }
        set {
            this.essentialitysupportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key-event-essentiality")]
    public dataAopKeyeventessentiality[] keyeventessentiality {
        get {
            return this.keyeventessentialityField;
        }
        set {
            this.keyeventessentialityField = value;
        }
    }
    
    /// <remarks/>
    public applicabilitytype applicability {
        get {
            return this.applicabilityField;
        }
        set {
            this.applicabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("overall-assessment")]
    public dataAopOverallassessment overallassessment {
        get {
            return this.overallassessmentField;
        }
        set {
            this.overallassessmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("potential-applications")]
    public string potentialapplications {
        get {
            return this.potentialapplicationsField;
        }
        set {
            this.potentialapplicationsField = value;
        }
    }
    
    /// <remarks/>
    public dataAopSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sourceSpecified {
        get {
            return this.sourceFieldSpecified;
        }
        set {
            this.sourceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("source-internal-id")]
    public string sourceinternalid {
        get {
            return this.sourceinternalidField;
        }
        set {
            this.sourceinternalidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uri")]
    public string[] uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    public string references {
        get {
            return this.referencesField;
        }
        set {
            this.referencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("aop-stressors")]
    [System.Xml.Serialization.XmlArrayItemAttribute("aop-stressor", IsNullable=false)]
    public dataAopAopstressor[] aopstressors {
        get {
            return this.aopstressorsField;
        }
        set {
            this.aopstressorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopMolecularinitiatingevent {
    
    private string evidencesupportingchemicalinitiationField;
    
    private string keyeventidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("evidence-supporting-chemical-initiation")]
    public string evidencesupportingchemicalinitiation {
        get {
            return this.evidencesupportingchemicalinitiationField;
        }
        set {
            this.evidencesupportingchemicalinitiationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("key-event-id")]
    public string keyeventid {
        get {
            return this.keyeventidField;
        }
        set {
            this.keyeventidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopAdverseoutcome {
    
    private string examplesField;
    
    private string regulatoryrelevanceField;
    
    private dataAopAdverseoutcomeOrgansaffected[] organsaffectedField;
    
    private string keyeventidField;
    
    /// <remarks/>
    public string examples {
        get {
            return this.examplesField;
        }
        set {
            this.examplesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("regulatory-relevance")]
    public string regulatoryrelevance {
        get {
            return this.regulatoryrelevanceField;
        }
        set {
            this.regulatoryrelevanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organs-affected")]
    public dataAopAdverseoutcomeOrgansaffected[] organsaffected {
        get {
            return this.organsaffectedField;
        }
        set {
            this.organsaffectedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("key-event-id")]
    public string keyeventid {
        get {
            return this.keyeventidField;
        }
        set {
            this.keyeventidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopAdverseoutcomeOrgansaffected : evidencetype {
    
    private string synonymField;
    
    private string scientificnameField;
    
    /// <remarks/>
    public string synonym {
        get {
            return this.synonymField;
        }
        set {
            this.synonymField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("scientific-name")]
    public string scientificname {
        get {
            return this.scientificnameField;
        }
        set {
            this.scientificnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopRelationship {
    
    private dataAopRelationshipDirectness directnessField;
    
    private confidenceleveltype quantitativeunderstandingvalueField;
    
    private confidenceleveltype evidenceField;
    
    private string idField;
    
    /// <remarks/>
    public dataAopRelationshipDirectness directness {
        get {
            return this.directnessField;
        }
        set {
            this.directnessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quantitative-understanding-value")]
    public confidenceleveltype quantitativeunderstandingvalue {
        get {
            return this.quantitativeunderstandingvalueField;
        }
        set {
            this.quantitativeunderstandingvalueField = value;
        }
    }
    
    /// <remarks/>
    public confidenceleveltype evidence {
        get {
            return this.evidenceField;
        }
        set {
            this.evidenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum dataAopRelationshipDirectness {
    
    /// <remarks/>
    direct,
    
    /// <remarks/>
    indirect,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopKeyeventessentiality {
    
    private string keyeventidField;
    
    private confidenceleveltype essentialitylevelField;
    
    private string[] uriField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key-event-id", DataType="positiveInteger")]
    public string keyeventid {
        get {
            return this.keyeventidField;
        }
        set {
            this.keyeventidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("essentiality-level")]
    public confidenceleveltype essentialitylevel {
        get {
            return this.essentialitylevelField;
        }
        set {
            this.essentialitylevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("uri")]
    public string[] uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopOverallassessment {
    
    private string descriptionField;
    
    private string applicabilityField;
    
    private string keyeventessentialitysummaryField;
    
    private string weightofevidencesummaryField;
    
    private string quantitativeconsiderationsField;
    
    private string uriField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string applicability {
        get {
            return this.applicabilityField;
        }
        set {
            this.applicabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("key-event-essentiality-summary")]
    public string keyeventessentialitysummary {
        get {
            return this.keyeventessentialitysummaryField;
        }
        set {
            this.keyeventessentialitysummaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("weight-of-evidence-summary")]
    public string weightofevidencesummary {
        get {
            return this.weightofevidencesummaryField;
        }
        set {
            this.weightofevidencesummaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quantitative-considerations")]
    public string quantitativeconsiderations {
        get {
            return this.quantitativeconsiderationsField;
        }
        set {
            this.quantitativeconsiderationsField = value;
        }
    }
    
    /// <remarks/>
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public enum dataAopSource {
    
    /// <remarks/>
    AOPWiki,
    
    /// <remarks/>
    Effectopedia,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Intermediate Effects DB")]
    IntermediateEffectsDB,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("AOP Xplorer")]
    AOPXplorer,
    
    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataAopAopstressor : evidencetype {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.aopkb.org/aop-xml")]
public partial class dataVendorspecific {
    
    private System.Xml.XmlElement[] anyField;
    
    private string idField;
    
    private string nameField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}
